spring:
  application:
    name: rabbitmq-provider
  # rabbitmq配置参数
  rabbitmq:
    host: 10.143.228.215
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
server:
  port: 8080
